### ISSUE TITLE
0.3.4 plus de connexion 

### ISSUE THREAD

**Issue by Egainmoney** [kamaradclimber/vigieau#18]
Salut depuis le passage a la 0.3.4 ce matin je n'ai plus de retour des infos tout est passer en Inconnu ? je viens de vérifier sur Vigieau tout est ok j'ai redémarrer plusieurs fois sans reussites

**Comment by Christophe69480** [comment]
idem
`Logger: homeassistant.components.sensor
Source: helpers/update_coordinator.py:258
Integration: Capteur (documentation, issues)
First occurred: 09:18:05 (2 occurrences)
Last logged: 09:18:22

Error while setting up vigieau platform for sensor
Error while setting up rte_ecowatt platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/vigieau/__init__.py", line 151, in update_method
    city_code = await self.fetch_insee_code()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vigieau/__init__.py", line 120, in fetch_insee_code
    raise UpdateFailed(
homeassistant.helpers.update_coordinator.UpdateFailed: Impossible to find approximate address of the current HA instance. API returned no result.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vigieau/__init__.py", line 189, in update_method
    raise UpdateFailed(f"Error communicating with API: {err}")
homeassistant.helpers.update_coordinator.UpdateFailed: Error communicating with API: Impossible to find approximate address of the current HA instance. API returned no result.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/vigieau/sensor.py", line 42, in async_setup_entry
    await vigieau_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Error communicating with API: Impossible to find approximate address of the current HA instance. API returned no result.
`

**Comment by kamaradclimber** [comment]
Good catch! Merci
