### ISSUE TITLE
Toujours pas de remontée

### ISSUE THREAD

**Issue by lrachet** [kamaradclimber/vigieau#23]
Bonjour,
Malgré les différentes mises à jour jusqu'à la 0.3.6, je n'ai toujours pas de remontée d'informations et je ne vois pas comment forcer le code INSEE.

Merci.

```
Logger: homeassistant.components.sensor
Source: custom_components/vigieau/__init__.py:220
Integration: Capteur (documentation, issues)
First occurred: 19:13:45 (1 occurrences)
Last logged: 19:13:45

Error while setting up vigieau platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/vigieau/sensor.py", line 42, in async_setup_entry
    await vigieau_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 251, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/config/custom_components/vigieau/__init__.py", line 220, in _handle_coordinator_update
    self._attr_icon = {
                      ^
KeyError: 'alerte renforcée'

```

**Comment by kamaradclimber** [comment]
Bonjour,

la 0.3.7 devrait corriger le problème. Je pense que ca n'a rien à voir avec code insee mais simplement avec le fait que je n'avais pas trouvé de commune en alerte renforcée jusqu'à présent.

**Comment by lrachet** [comment]
Super. Merci.

**Comment by lrachet** [comment]
Bonjour,
Toujours exactement le même problème.

**Comment by kamaradclimber** [comment]
Bonjour,

pourrais-je avoir le nom de la commune pour reproduire de mon coté?

**Comment by lrachet** [comment]
Sainte-Anne-Sur-Brivet 44160

Merci.

Le lun. 24 juil. 2023, 16:22, Grégoire Seux ***@***.***> a
écrit :

**Comment by kamaradclimber** [comment]
La 0.3.8 devrait corriger le problème pour de bon

**Comment by lrachet** [comment]
Tout fonctionne avec la 0.3.10. Merci.
