### ISSUE TITLE
Support alert_renforcee

### ISSUE THREAD

**Issue by kamaradclimber** [kamaradclimber/vigieau#61]
Bonjour,
Cela ne fonctionne toujours pas chez moi voici les logs de Ha.
J'ai essai de supprimer et remettre l'integration avec redémarrage mais rien n'y fait.
J'ai les capteurs en inconnu sauf celui des prélèvements d'eau en canaux qui fonctionne

Home Assistant

Core
2024.5.3
Supervisor
2024.05.1
Operating System
12.3
Interface utilisateur
20240501.1

```
Enregistreur: homeassistant.components.sensor
Source: helpers/entity_platform.py:356
intégration: Capteur (documentation, problèmes)
S'est produit pour la première fois: 18:39:17 (1 occurrences)
Dernier enregistrement: 18:39:17

Error while setting up vigieau platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/vigieau/sensor.py", line 29, in async_setup_entry
    await vigieau_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 414, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/vigieau/__init__.py", line 239, in _handle_coordinator_update
    self._attr_icon = {
                      ^
KeyError: 'alerte_renforcee'
```
```
Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.vigieau
Source: custom_components/vigieau/__init__.py:387
intégration: Vigieau (documentation, problèmes)
S'est produit pour la première fois: 18:39:17 (13 occurrences)
Dernier enregistrement: 18:39:17

Restrictions are hard to interpret: ['Interdit sauf pour les usages commerciaux après accord du service de police de l’eau.', 'Interdit sauf pour les usages commerciaux après accord du service de police de l’eau.']
Restrictions are hard to interpret: ['Selon les enjeux, un arrêté municipal ou un arrêté préfectoral spécifique peut être pris en cas d’impact sur la biodiversité, pour limiter l’accès ou site ou\nl’exercice de l’activité.', 'Privilégier le regroupement des bateaux pour le passage des écluses.', 'Interdiction.', 'Interdiction.', 'Interdiction à l’exception des cas suivants :\n- situation d’assec total après déclaration au service police de l’eau de la DDTM,\n- pour des raisons de sécurité publique après déclaration au service police de l’eau de la DDTM,\n- pour les travaux d’une durée dépassant 1 mois, sur avis préalable spécifique de l’OFB et du service de police de l’eau au regard de\nla situation hydrologique du site (débit au moment des travaux, permanence de l’écoulement) et de la nature des travaux.']
Restrictions are hard to interpret: ['Privilégier le regroupement des bateaux pour le passage des écluses.']
Restrictions are hard to interpret: ['Interdiction sauf pour les greens et départs\nuniquement dans le cadre d’un plan de\ngestion spécifique permettant une économie\nd’eau de 30% par rapport à l’usage hors\nsécheresse sur une même surface.\n\nLe plan de gestion proposera un volume\nhebdomadaire maximal 280 m3/semaine pour\n9 trous,\n- entre 20h et 8h du 1er avril au 30 septembre\n- entre 18h et 10h du 1er octobre au 31 mars.']
Restrictions are hard to interpret: ['Pas de restriction sauf arrêté spécifique.', 'Interdiction.\nL’usage d’eau brute est également interdit pour des raisons sanitaires pour les usages type baignade.']
```

_Originally posted by @lafefe in https://github.com/kamaradclimber/vigieau/issues/58#issuecomment-2108178622_

**Comment by kamaradclimber** [comment]
@lafefe, https://github.com/kamaradclimber/vigieau/releases/tag/0.5.1 devrait corriger le problème. Bien vu!

**Comment by lafefe** [comment]
Bonjour,
Et merci pour ta réactivité cela a fonctionné pour l'alerte générale mais sur les autres sensors pas du tout.

```
Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.vigieau
Source: custom_components/vigieau/__init__.py:388
intégration: Vigieau (documentation, problèmes)
S'est produit pour la première fois: 21:45:30 (26 occurrences)
Dernier enregistrement: 21:52:56

Restrictions are hard to interpret: ['Interdit sauf pour les usages commerciaux après accord du service de police de l’eau.', 'Interdit sauf pour les usages commerciaux après accord du service de police de l’eau.']
Restrictions are hard to interpret: ['Selon les enjeux, un arrêté municipal ou un arrêté préfectoral spécifique peut être pris en cas d’impact sur la biodiversité, pour limiter l’accès ou site ou\nl’exercice de l’activité.', 'Privilégier le regroupement des bateaux pour le passage des écluses.', 'Interdiction.', 'Interdiction.', 'Interdiction à l’exception des cas suivants :\n- situation d’assec total après déclaration au service police de l’eau de la DDTM,\n- pour des raisons de sécurité publique après déclaration au service police de l’eau de la DDTM,\n- pour les travaux d’une durée dépassant 1 mois, sur avis préalable spécifique de l’OFB et du service de police de l’eau au regard de\nla situation hydrologique du site (débit au moment des travaux, permanence de l’écoulement) et de la nature des travaux.']
Restrictions are hard to interpret: ['Privilégier le regroupement des bateaux pour le passage des écluses.']
Restrictions are hard to interpret: ['Interdiction sauf pour les greens et départs\nuniquement dans le cadre d’un plan de\ngestion spécifique permettant une économie\nd’eau de 30% par rapport à l’usage hors\nsécheresse sur une même surface.\n\nLe plan de gestion proposera un volume\nhebdomadaire maximal 280 m3/semaine pour\n9 trous,\n- entre 20h et 8h du 1er avril au 30 septembre\n- entre 18h et 10h du 1er octobre au 31 mars.']
Restrictions are hard to interpret: ['Pas de restriction sauf arrêté spécifique.', 'Interdiction.\nL’usage d’eau brute est également interdit pour des raisons sanitaires pour les usages type baignade.']
```

![Screenshot_2024-05-13-21-58-37-86_c3a231c25ed346e59462e84656a70e50](https://github.com/kamaradclimber/vigieau/assets/97065167/881c7e8b-a224-43e9-9d15-e3350c8cc744)

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/vigieau/releases/tag/0.5.2 devrait aider mais je pense que la situation va se reproduire fréquemment à chaque nouvel arrêté.
