### ISSUE TITLE
Erreur sensor Alert level depuis V0.7.4

### ISSUE THREAD

**Issue by Patrick44fr** [kamaradclimber/vigieau#84]
Bonjour, je viens d'installer la dernière version de vigieeau et je l'utilise sur 2 instances différentes d'home assistant et j'ai la même erreur pour 2 site différents 44182 et 44198.
voici l'un des logs
```
2024-11-23 12:03:51.365 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up vigieau platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/vigieau/sensor.py", line 29, in async_setup_entry
    await vigieau_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 309, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 481, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 176, in async_update_listeners
    update_callback()
  File "/config/custom_components/vigieau/__init__.py", line 259, in _handle_coordinator_update
    self._attr_icon = {
                      ^
KeyError: 'vigilance_(pas_de_restriction)'
```

Integration version: 0.7.4
Home-Assistant version: 2024.11.03

Merci pour tout le travail déjà accompli et la résolution de cette anomalie

j'en profite pour signaler une coquille la version ne s'incrémente pas sous l'intégration.
![image](https://github.com/user-attachments/assets/d2c846b7-2833-4ac1-8eb7-e0c2b3040647)

**Comment by Skuair** [comment]
Pareil de mon côté depuis la dernière version, même message d'erreur et état de l'entité à "unknown".

**Comment by kamaradclimber** [comment]
Merci à tous les deux!
